Add ana and ana_action tests
hazelgrove/diy-hazelnut pull request #9
Opened 2024-03-01 20:38 UTC by jpoly1219

**Motivation:**
Adds to #7.

I added `erase_exp` and `syn` tests on the last pull request that has been merged. That left me with `ana`, `syn_action`, and `ana_action` to implement. Razeen Maroof and I decided to split the load into two, where I decided to implement `ana` and `ana_action`.

**Changes:** 
- Add `ana` and `ana_action` tests.
- Make types printable using `ppx_deriving.show`
- Update Makefile to include `ppx_deriving.show` as dependency

2024-03-21 17:09 UTC, cyrus- commented
@jpoly1219 does this handle all of the rules from the paper? if not, can you create a progress checklist similar to https://github.com/hazelgrove/hazel/pull/1197 with all of the rule names from the paper?

2025-01-13 01:37 UTC, cyrus- requested changes

2025-01-13 01:37 UTC, cyrus- commented on test/Test_type_action.re
> +    Some((RAsc(Lit(1), RArrow(Num,Cursor(Hole))), Arrow(Num,Hole)));
this is not correct

2025-01-13 03:05 UTC, CyrusD123 commented on test/Test_type_action.re
> +    Some((RAsc(Lit(1), RArrow(Num,Cursor(Hole))), Arrow(Num,Hole)));
Should be fixed now. I wrapped the literal in a lambda expression

2025-07-15 00:45 UTC, cyrus- approved these changes

2025-07-15 00:45 UTC, merged